// Code generated by protoc-gen-go. DO NOT EDIT.
// source: groupsig.proto

package groupsig

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ECP is an elliptic curve point specified by its coordinates
// ECP corresponds to an element of the first group (G1)
type ECP struct {
	X                    []byte   `protobuf:"bytes,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    []byte   `protobuf:"bytes,2,opt,name=Y,proto3" json:"Y,omitempty"`
}

func (m *ECP) Reset()         { *m = ECP{} }
func (m *ECP) String() string { return proto.CompactTextString(m) }
func (*ECP) ProtoMessage()    {}
func (*ECP) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupsig_56a295adc5f2d583, []int{0}
}

func (m *ECP) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *ECP) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

// ECP2 is an elliptic curve point specified by its coordinates
// ECP2 corresponds to an element of the second group (G2)
type ECP2 struct {
	XA                   []byte   `protobuf:"bytes,1,opt,name=XA,proto3" json:"XA,omitempty"`
	XB                   []byte   `protobuf:"bytes,2,opt,name=XB,proto3" json:"XB,omitempty"`
	YA                   []byte   `protobuf:"bytes,3,opt,name=YA,proto3" json:"YA,omitempty"`
	YB                   []byte   `protobuf:"bytes,4,opt,name=YB,proto3" json:"YB,omitempty"`
}

func (m *ECP2) Reset()         { *m = ECP2{} }
func (m *ECP2) String() string { return proto.CompactTextString(m) }
func (*ECP2) ProtoMessage()    {}
func (*ECP2) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupsig_56a295adc5f2d583, []int{1}
}

func (m *ECP2) GetXA() []byte {
	if m != nil {
		return m.XA
	}
	return nil
}

func (m *ECP2) GetXB() []byte {
	if m != nil {
		return m.XB
	}
	return nil
}

func (m *ECP2) GetYA() []byte {
	if m != nil {
		return m.YA
	}
	return nil
}

func (m *ECP2) GetYB() []byte {
	if m != nil {
		return m.YB
	}
	return nil
}

// GroupMasterKey specifies a group master secret key that consists of
// gmsk - a random integer used to generate users' secret keys
type GroupMasterKey struct {
	Sk                   []byte   `protobuf:"bytes,1,opt,name=Sk,proto3" json:"Sk,omitempty"`
}

func (m *GroupMasterKey) Reset()         { *m = GroupMasterKey{} }
func (m *GroupMasterKey) String() string { return proto.CompactTextString(m) }
func (*GroupMasterKey) ProtoMessage()    {}
func (*GroupMasterKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupsig_56a295adc5f2d583, []int{2}
}

func (m *GroupMasterKey) GetSk() []byte {
	if m != nil {
		return m.Sk
	}
	return nil
}

// TracingKey specifies a group tracing key that consists of
// TK1,TK2 - random integers
type TracingKey struct {
	TK1                  []byte   `protobuf:"bytes,1,opt,name=TK1,proto3" json:"TK1,omitempty"`
	TK2                  []byte   `protobuf:"bytes,2,opt,name=TK2,proto3" json:"TK2,omitempty"`
}

func (m *TracingKey) Reset()         { *m = TracingKey{} }
func (m *TracingKey) String() string { return proto.CompactTextString(m) }
func (*TracingKey) ProtoMessage()    {}
func (*TracingKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupsig_56a295adc5f2d583, []int{3}
}

func (m *TracingKey) GetTK1() []byte {
	if m != nil {
		return m.TK1
	}
	return nil
}

func (m *TracingKey) GetTK2() []byte {
	if m != nil {
		return m.TK2
	}
	return nil
}

// GroupPublicKey specifies a group public key that consists of
// u,v,h - group elements corresponding to the group signing key
type GroupPublicKey struct {
	U                    *ECP     `protobuf:"bytes,1,opt,name=U,proto3" json:"U,omitempty"`
	V                    *ECP     `protobuf:"bytes,2,opt,name=V,proto3" json:"V,omitempty"`
	H                    *ECP     `protobuf:"bytes,3,opt,name=H,proto3" json:"H,omitempty"`
	W                    *ECP2    `protobuf:"bytes,4,opt,name=W,proto3" json:"W,omitempty"`
}

func (m *GroupPublicKey) Reset()         { *m = GroupPublicKey{} }
func (m *GroupPublicKey) String() string { return proto.CompactTextString(m) }
func (*GroupPublicKey) ProtoMessage()    {}
func (*GroupPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupsig_56a295adc5f2d583, []int{4}
}

func (m *GroupPublicKey) GetU() *ECP {
	if m != nil {
		return m.U
	}
	return nil
}

func (m *GroupPublicKey) GetV() *ECP {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *GroupPublicKey) GetH() *ECP {
	if m != nil {
		return m.H
	}
	return nil
}

func (m *GroupPublicKey) GetW() *ECP2 {
	if m != nil {
		return m.W
	}
	return nil
}

// GroupKey specifies a group key that consists of
// TK - group tracing key
// GPK - group public key
type GroupKey struct {
	Gmsk                 *GroupMasterKey `protobuf:"bytes,1,opt,name=gmsk,proto3" json:"gmsk,omitempty"`
	TK                   *TracingKey     `protobuf:"bytes,2,opt,name=TK,proto3" json:"TK,omitempty"`
	GPK                  *GroupPublicKey `protobuf:"bytes,3,opt,name=GPK,proto3" json:"GPK,omitempty"`
}

func (m *GroupKey) Reset()         { *m = GroupKey{} }
func (m *GroupKey) String() string { return proto.CompactTextString(m) }
func (*GroupKey) ProtoMessage()    {}
func (*GroupKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupsig_56a295adc5f2d583, []int{5}
}

func (m *GroupKey) GetGmsk() *GroupMasterKey {
	if m != nil {
		return m.Gmsk
	}
	return nil
}

func (m *GroupKey) GetTK() *TracingKey {
	if m != nil {
		return m.TK
	}
	return nil
}

func (m *GroupKey) GetGPK() *GroupPublicKey {
	if m != nil {
		return m.GPK
	}
	return nil
}

// UserKey specifies a user's private key pair that consists of
// UK1 - a random integer
// UK2 - an element corresponding to the private key
type UserKey struct {
	UK1                  []byte   `protobuf:"bytes,1,opt,name=UK1,proto3" json:"UK1,omitempty"`
	UK2                  *ECP     `protobuf:"bytes,2,opt,name=UK2,proto3" json:"UK2,omitempty"`
}

func (m *UserKey) Reset()         { *m = UserKey{} }
func (m *UserKey) String() string { return proto.CompactTextString(m) }
func (*UserKey) ProtoMessage()    {}
func (*UserKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupsig_56a295adc5f2d583, []int{6}
}

func (m *UserKey) GetUK1() []byte {
	if m != nil {
		return m.UK1
	}
	return nil
}

func (m *UserKey) GetUK2() *ECP {
	if m != nil {
		return m.UK2
	}
	return nil
}

// Signature specifies a signature object that consists of
// and the corresponding user secret together with the attribute values
type GroupSignature struct {
	T1                   *ECP     `protobuf:"bytes,1,opt,name=T1,proto3" json:"T1,omitempty"`
	T2                   *ECP     `protobuf:"bytes,2,opt,name=T2,proto3" json:"T2,omitempty"`
	T3                   *ECP     `protobuf:"bytes,3,opt,name=T3,proto3" json:"T3,omitempty"`
	ProofC               []byte   `protobuf:"bytes,4,opt,name=ProofC,proto3" json:"ProofC,omitempty"`
	ProofSalpha          []byte   `protobuf:"bytes,5,opt,name=ProofSalpha,proto3" json:"ProofSalpha,omitempty"`
	ProofSbeta           []byte   `protobuf:"bytes,6,opt,name=ProofSbeta,proto3" json:"ProofSbeta,omitempty"`
	ProofSx              []byte   `protobuf:"bytes,7,opt,name=ProofSx,proto3" json:"ProofSx,omitempty"`
	ProofSdelta1         []byte   `protobuf:"bytes,8,opt,name=ProofSdelta1,proto3" json:"ProofSdelta1,omitempty"`
	ProofSdelta2         []byte   `protobuf:"bytes,9,opt,name=ProofSdelta2,proto3" json:"ProofSdelta2,omitempty"`
}

func (m *GroupSignature) Reset()         { *m = GroupSignature{} }
func (m *GroupSignature) String() string { return proto.CompactTextString(m) }
func (*GroupSignature) ProtoMessage()    {}
func (*GroupSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupsig_56a295adc5f2d583, []int{7}
}

func (m *GroupSignature) GetT1() *ECP {
	if m != nil {
		return m.T1
	}
	return nil
}

func (m *GroupSignature) GetT2() *ECP {
	if m != nil {
		return m.T2
	}
	return nil
}

func (m *GroupSignature) GetT3() *ECP {
	if m != nil {
		return m.T3
	}
	return nil
}

func (m *GroupSignature) GetProofC() []byte {
	if m != nil {
		return m.ProofC
	}
	return nil
}

func (m *GroupSignature) GetProofSalpha() []byte {
	if m != nil {
		return m.ProofSalpha
	}
	return nil
}

func (m *GroupSignature) GetProofSbeta() []byte {
	if m != nil {
		return m.ProofSbeta
	}
	return nil
}

func (m *GroupSignature) GetProofSx() []byte {
	if m != nil {
		return m.ProofSx
	}
	return nil
}

func (m *GroupSignature) GetProofSdelta1() []byte {
	if m != nil {
		return m.ProofSdelta1
	}
	return nil
}

func (m *GroupSignature) GetProofSdelta2() []byte {
	if m != nil {
		return m.ProofSdelta2
	}
	return nil
}

// K specifies a user's private key that is decrypted by CA
type K struct {
	Ax                   *ECP     `protobuf:"bytes,1,opt,name=Ax,proto3" json:"Ax,omitempty"`
}

func (m *K) Reset()         { *m = K{} }
func (m *K) String() string { return proto.CompactTextString(m) }
func (*K) ProtoMessage()    {}
func (*K) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupsig_56a295adc5f2d583, []int{8}
}

func (m *K) GetAx() *ECP {
	if m != nil {
		return m.Ax
	}
	return nil
}

func init() {
	proto.RegisterType((*ECP)(nil), "ECP")
	proto.RegisterType((*ECP2)(nil), "ECP2")
	proto.RegisterType((*GroupMasterKey)(nil), "GroupMasterKey")
	proto.RegisterType((*TracingKey)(nil), "TracingKey")
	proto.RegisterType((*GroupPublicKey)(nil), "GroupPublicKey")
	proto.RegisterType((*GroupKey)(nil), "GroupKey")
	proto.RegisterType((*UserKey)(nil), "UserKey")
	proto.RegisterType((*GroupSignature)(nil), "GroupSignature")
	proto.RegisterType((*K)(nil), "K")
}

func init() { proto.RegisterFile("groupsig.proto", fileDescriptor_groupsig_56a295adc5f2d583) }

var fileDescriptor_groupsig_56a295adc5f2d583 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x93, 0x6f, 0x8b, 0xda, 0x40,
	0x10, 0xc6, 0xd9, 0x8d, 0xa7, 0x76, 0x14, 0x7b, 0x6c, 0xcb, 0xb1, 0xa5, 0x50, 0xbc, 0xed, 0x9b,
	0xbe, 0x92, 0x66, 0xfd, 0x04, 0x89, 0xd8, 0x3b, 0x08, 0x85, 0x10, 0x93, 0xbb, 0xa4, 0xef, 0xd6,
	0x6b, 0x9a, 0x8a, 0xf6, 0x22, 0x49, 0x04, 0xfb, 0x25, 0xfa, 0x99, 0xcb, 0x4c, 0x56, 0xcf, 0xb4,
	0xef, 0xe6, 0xf9, 0x3d, 0xf3, 0x67, 0x67, 0x42, 0x60, 0x52, 0x54, 0xe5, 0x61, 0x5f, 0x6f, 0x8a,
	0xd9, 0xbe, 0x2a, 0x9b, 0x52, 0xdd, 0x82, 0xb3, 0x5c, 0x84, 0x62, 0x0c, 0x2c, 0x95, 0x6c, 0xca,
	0x3e, 0x8d, 0x23, 0x96, 0xa2, 0xca, 0x24, 0x6f, 0x55, 0xa6, 0xbe, 0x40, 0x6f, 0xb9, 0x08, 0xb5,
	0x98, 0x00, 0x4f, 0x3d, 0x9b, 0xc4, 0x53, 0x8f, 0xb4, 0x6f, 0xd3, 0x78, 0xea, 0xa3, 0xce, 0x3c,
	0xe9, 0xb4, 0x3a, 0x23, 0x3f, 0xf3, 0x65, 0xcf, 0x6a, 0x5f, 0x4d, 0x61, 0x72, 0x87, 0xc3, 0xbf,
	0x9a, 0xba, 0xc9, 0xab, 0x20, 0xff, 0x8d, 0x19, 0xab, 0xed, 0xa9, 0xe3, 0x6a, 0xab, 0x3e, 0x03,
	0xc4, 0x95, 0x79, 0xda, 0x3c, 0x17, 0xe8, 0x5e, 0x83, 0x13, 0x07, 0xae, 0xb5, 0x31, 0x6c, 0x89,
	0xb6, 0x23, 0x31, 0x54, 0xc6, 0xf6, 0x0c, 0x0f, 0xeb, 0xdd, 0xe6, 0x09, 0xab, 0x04, 0xb0, 0x84,
	0x6a, 0x46, 0xba, 0x37, 0x5b, 0x2e, 0xc2, 0x88, 0x25, 0xc8, 0x1e, 0xa8, 0xea, 0xcc, 0x1e, 0x90,
	0xdd, 0xd3, 0x63, 0xcf, 0xec, 0x5e, 0xbc, 0x01, 0xf6, 0x48, 0x0f, 0x1e, 0xe9, 0x2b, 0x64, 0x3a,
	0x62, 0x8f, 0xaa, 0x84, 0x21, 0x8d, 0xc0, 0xe6, 0x1f, 0xa1, 0x57, 0xfc, 0xaa, 0xb7, 0xb6, 0xff,
	0xeb, 0x59, 0x77, 0x9f, 0x88, 0x4c, 0xf1, 0x1e, 0x78, 0x1c, 0xd8, 0x71, 0xa3, 0xd9, 0xcb, 0x42,
	0x11, 0x8f, 0x03, 0x71, 0x0b, 0xce, 0x5d, 0x18, 0xd8, 0xc1, 0xb6, 0xc1, 0xf9, 0xf1, 0x11, 0x7a,
	0x6a, 0x0e, 0x83, 0xa4, 0x6e, 0x0f, 0x74, 0x0d, 0x4e, 0xf2, 0x72, 0x82, 0x24, 0x70, 0xc5, 0x0d,
	0x12, 0xdd, 0x59, 0x06, 0x81, 0xfa, 0xc3, 0xed, 0x25, 0x56, 0x9b, 0xe2, 0xd9, 0x34, 0x87, 0x2a,
	0x17, 0x6f, 0x81, 0xc7, 0x6e, 0xe7, 0x14, 0x3c, 0x76, 0x89, 0x76, 0xeb, 0x79, 0xac, 0x89, 0xce,
	0x3b, 0xe7, 0xe0, 0xf1, 0x5c, 0xdc, 0x40, 0x3f, 0xac, 0xca, 0xf2, 0xc7, 0xc2, 0x7e, 0x45, 0xab,
	0xc4, 0x14, 0x46, 0x14, 0xad, 0xcc, 0x6e, 0xff, 0xd3, 0xc8, 0x2b, 0x32, 0x2f, 0x91, 0xf8, 0x00,
	0xd0, 0xca, 0x75, 0xde, 0x18, 0xd9, 0xa7, 0x84, 0x0b, 0x22, 0x24, 0x0c, 0x5a, 0x75, 0x94, 0x03,
	0x32, 0x4f, 0x52, 0x28, 0x18, 0xb7, 0xe1, 0xf7, 0x7c, 0xd7, 0x18, 0x57, 0x0e, 0xc9, 0xee, 0xb0,
	0x7f, 0x72, 0xb4, 0x7c, 0xf5, 0x5f, 0x8e, 0x56, 0xef, 0x80, 0x05, 0xb8, 0x96, 0x77, 0xec, 0x9e,
	0xc0, 0x3b, 0xfa, 0xf0, 0x6d, 0x78, 0xfa, 0x0b, 0xd6, 0x7d, 0xfa, 0x0d, 0xe6, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xae, 0xe4, 0x23, 0xba, 0x18, 0x03, 0x00, 0x00,
}
